### PR TITLE
Check if unit is player before calling expensive update function

### PR DESCRIPTION
**Pull request by xeropresence**

### CODE REVIEW

**Comment by cont1nuity** [comment]
The call is not expensive for executes outside of BGs/Arena and will be executed inside BGs/Arena anyways.
I'll rethink how it might be handled.
In addition: `unit` needs a `nil` check anyways.

**Comment by xeropresence** [comment]
Issue is for things like pets in battlegrounds, and npcs in epic battlegrounds will trigger the scoreboard parsing. I don't think adding a nil check would be any faster since unitisplayer most likely checks that from what i recall.

**Comment by cont1nuity** [comment]
That's true, pets and npcs are an issue. `nil` checks are needed in addition.

**Comment by xeropresence** [comment]
Under what situation does nil get passed in anyway? I haven't looked at the api but I assumed for the "worst" case the unitname would be passed as unitnames are a valid unitid

**Comment by cont1nuity** [comment]
Thank you for your contribution!

**Pull request merged**
