### PR TITLE
- Adding enrage to normal / special buff tracking and '.auraType' to the auraIconFrame

### PR DESCRIPTION
**Pull request by cont1nuity**
Adding the auraType to the auraIconFrame to start supporting rage effect tracking. Can be used to track any other aura type as well:
Disease", "Poison", "Curse", "Magic", "" (yes, empty string. this is how Blizzard rolls apparently) for enrage and nil/"none" for uncategorized.

### CODE REVIEW

**Comment by cont1nuity** [comment]
Added options to select tracking and border color of enrage effects for normal and special buff tracking.

**Comment by Tercioo** [comment]
Let's use capital letter to initialize a variable considered "exported to script", it'll be iconFrame.AuraType
I know, there's a lot of inconsistency on my own code on this regards but I'm trying to apply this to new variables.

**Comment by Tercioo** [comment]
In the future if blizzard fixes the "" for enrage, all scripts that use it will be broken, also just "" is too vague as well.
It'll be great to have an easy to read value to export to scripts, maybe a function convert blizzard aura type standards to some Plater custom types like "enrage", "poison", etc. Example: 
iconFrame.AuraType = convert_script_aura_type (actualAuraType)

**Comment by cont1nuity** [comment]
How about AuraType constants, such as Plater.AURA_TYPE_ENRAGE? Can be easily changed if Blizzard decides to "fix" things up a bit.
I think this is feasible fo script/mod usage as well and easier to handle for mod/script creators.
I agree with the capital public variables. This should be consistent.

**Comment by Tercioo** [comment]
On the Plater side, you can do the way you think it's better.
But for the script side is important it receives a clear indication of the type, e.g. "enrage", "poison", "curse", "magic", etc.

**Comment by cont1nuity** [comment]
I have added constants for the aura types and made readable values public for mods/scripts.
Added _CanStealOrPurge in addition to _AuraType for scripting in scriptEnv

**Comment by Tercioo** [comment]
Much better now. 

Let's format the aura types which is exposed to scripts using lower case, example "enrage", "magic", etc. This is due to .ActorType strings using lower letters such as "enemyplayer", "friendlynpc".

AURA_TYPE_DISEASE is missing on local AURA_TYPES = {

["Macig"] = "MAGIC", I think there's a typo on "Macig".

**Comment by cont1nuity** [comment]
I need to stop doing this in the middle of the night...
And I need to start taking notes on consistency requirements.

**Comment by Tercioo** [comment]
Oh you're doing great, no worries.
I think it's all okay now, let's wait major guilds to finish the new 2 boss raid content to push it to Alpha.

**Comment by cont1nuity** [comment]
Yeah, best to not interfere there. 👍 
This should still be mergeable even within a few weeks. Not planning to change much on that for now.

**Comment by cont1nuity** [comment]
Yeah, best to not interfere there. 👍 
This should still be mergeable even within a few weeks.
I am thinking of adding a tracking to the BuffFrames, e.g. "hasEnrage" and a function to check for a specific unitFrame, e.g. "Plater.IsUnitEnraged". This should be updated automatically during the buff tracking. Your thoughts?

**Comment by Tercioo** [comment]
Since you're caching the type of the aura, I'd say something more generic like: Plater.NameplateHasAuraType (unitFrame, auraType)
This covers not only "enrage" but all other types.

**Comment by cont1nuity** [comment]
My thoughts were about Plater.UnitHasAuraType, so maybe both can be implemented, but the unit check has more value, I think. NamePlateHasAuraType could be done by an additional boolean parameter.
At the moment only "shown" auras are cached inderectly on the BuffFrame, BuffFrame2 and ExtraIconFrame.
So we would need to introduce caching to ensure the values are filled even if the buff/debuff is not shown.
This would need some additional rework on Plater.UpdateAuras_* functions, which should not be a huge issue.
The design for the cache needs some thinking. In the first place I thought about adding simple booleans to the unitFrame, such as "hasEnrageEffect" or similar. After giving it a bit more thought, a whole aura cache for the unit could be interesting, such as:
```
UNIT_AURA_CACHE[unit] = {
  ["auras"] = {
    [<spellID>] = {
      <meta-info>
    },
  },
 hasEnrage = true,
}
```
This cache needs to be repopulated with each update function and cleared on hide/death, etc. with the whole BuffFrames.

**Comment by Tercioo** [comment]
That might spend too much resources creating tables on a feature that won't be used for the majority of the user base.

You may do a fast cache with unitFrame.AuraCache [spellId] = true and unitFrame.AuraCache [spellName] = true

You may create Plater.UnitAura (unitId, auraName / spellId) making it loop through auras returning the data.

**Pull request merged**
