### PR TITLE
Add toggle for ignoring per unit combat check

### PR DESCRIPTION
**Pull request by Jaden-Giordano**
This logic was removed in 9.0.1.307 and makes testing combat variants of plates kinda annoying.

There are two routes this could take:

1. The one I did which is just a checkbox that brings back the old logic.
2. Doing something similar to testing castbars and buffs by having a button to toggle the in combat state.

I am willing to update it to the second if that seems like the better option.

Also I was having issues getting the addon to load via a clone. It seems there are some build steps that are missing from the docs? If I could get some guidance on that so I can actually test this out correctly it would be appreciated!

### CODE REVIEW

**Comment by cont1nuity** [comment]
Thank you, but the implementation will look slightly different and the option needs to move.
It will be available in one of the next version.

**Comment by cont1nuity** [comment]
For everything else: join the Discord.

**Comment by Jaden-Giordano** [comment]
I mean I would really like to contribute, this is an open source repo for a reason and your focus lays else where in the project and most of the work for this feature is already done in this PR. Why not allow contribution, what could I change or how would you like to see this option available? What is it missing?

**Comment by cont1nuity** [comment]
Because there is still more work to do on other ends which came up recently. It not just this one part which needs to be altered.

**Comment by cont1nuity** [comment]
See c1281e1

**Pull request closed without merging**
