### PR TITLE
Add cardboard assassin to 'attacking specific units' mod

### PR DESCRIPTION
**Pull request by michaelbull**
This change adds the [Cardboard Assassin NPC](https://www.wowhead.com/npc=51229/cardboard-assassin) to the list of NPCs in the "Attacking Specific Unit" mod. This NPC is spawned from the [Cardboard Assassin engineering tinker](https://www.wowhead.com/spell=84425/cardboard-assassin) and is used a lot within [Mythic Plus dungeons](https://www.wowhead.com/news/mythic-tip-of-the-week-help-your-tank-with-cataclysms-cardboard-assassin-321768).

### CODE REVIEW

**Comment by cont1nuity** [comment]
Those are getting nerfed to death in 9.1, so I don't see any reason to add them as baseline to the mod.

**Comment by michaelbull** [comment]
@cont1nuity are they? They are added to the tournament realms of The Great Push right now, and I don't see any info in the released 9.1 suggesting a nerf to them.

**Comment by cont1nuity** [comment]
Yes, I was going to link that same article.

**Comment by michaelbull** [comment]
Yeah makes sense. I suppose unless it still sees ample play in M+ next patch there is not much point in merging this change. Thanks for the response.

**Comment by cont1nuity** [comment]
I don't think they will be useful in endgame content any time in the future after 9.1 hits, but we'll see.

**Pull request closed without merging**
