### PR TITLE
-fixing named quest mob recognition

### PR DESCRIPTION
**Pull request by cont1nuity**
If the quest mob has the same name as the quest, the QuestAmountCurrent and QuestAmountTotal were not recognized properly.

### CODE REVIEW

**Comment by Tercioo** [comment]
Hey, can you test is this won't break the quest color for mobs on world quests that require to fill a bar to 100%? I'm just thinking because those quest there's no min/max amount of mobs so they will fail that check I think.

**Comment by cont1nuity** [comment]
Indeed, that could be the case. I will test it out.

**Comment by cont1nuity** [comment]
Are there other types of quests than % oder #/#?

**Comment by Tercioo** [comment]
There's some quests that aren't for kill mobs like the one that require to feed a mob in Voldun and other quests that need to kill mobs to grab something from the loot to perform some action, etc.

**Pull request closed without merging**
